apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-java-app
  labels:
    app: my-java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-java-app
  template:
    metadata:
      labels:
        app: my-java-app
    spec:
      containers:
        - name: myjava-app
          image: jaykay84/java-app:mysqldb
          imagePullPolicy: Always
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: username
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password
            - name: DB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: database_server
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db_name
          ports:
            - containerPort: 8080